/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.MainFrame;

import business.DB4OUtil.DB4OUtil;
import business.EcoSystem;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import business.EcoSystem;
import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import javax.swing.UIManager;
/**
 *
 * @author Jyothi
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
         private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public MainJFrame() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
        this.pack();
        this.setSize(1425, 905);
//        this.setExtendedState(MainJFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopPanel = new javax.swing.JPanel();
        TopPanel1 = new javax.swing.JPanel();
        NamejLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        SignupjButton1 = new javax.swing.JButton();
        SigninjButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SignupjButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        SigninjButton = new javax.swing.JButton();
        NamejLabel = new javax.swing.JLabel();
        NamejLabel2 = new javax.swing.JLabel();
        NamejLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TopPanel.setBackground(new java.awt.Color(59, 63, 66));
        TopPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TopPanel1.setBackground(new java.awt.Color(51, 51, 51));
        TopPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NamejLabel1.setFont(new java.awt.Font("Arial", 1, 75)); // NOI18N
        NamejLabel1.setForeground(new java.awt.Color(255, 204, 255));
        NamejLabel1.setText("H.E.R");
        TopPanel1.add(NamejLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 210, 80));

        TopPanel.add(TopPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 1410, -1));

        jPanel2.setBackground(new java.awt.Color(244, 241, 222));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(244, 241, 222));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -230, 1070, 830));

        SignupjButton1.setBackground(new java.awt.Color(129, 178, 154));
        SignupjButton1.setFont(new java.awt.Font("Monaco", 1, 24)); // NOI18N
        SignupjButton1.setForeground(new java.awt.Color(61, 64, 91));
        SignupjButton1.setText("Sign Up");
        SignupjButton1.setBorderPainted(false);
        SignupjButton1.setContentAreaFilled(false);
        SignupjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupjButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(SignupjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 140, -1));

        SigninjButton1.setBackground(new java.awt.Color(129, 178, 154));
        SigninjButton1.setFont(new java.awt.Font("Monaco", 1, 24)); // NOI18N
        SigninjButton1.setForeground(new java.awt.Color(61, 64, 91));
        SigninjButton1.setText("Sign In");
        SigninjButton1.setBorderPainted(false);
        SigninjButton1.setContentAreaFilled(false);
        SigninjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SigninjButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(SigninjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 170, -1));

        TopPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 113, 1410, 750));

        getContentPane().add(TopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1410, 110));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));

        jLabel1.setBackground(new java.awt.Color(244, 241, 222));
        jPanel3.add(jLabel1);

        SignupjButton.setBackground(new java.awt.Color(129, 178, 154));
        SignupjButton.setFont(new java.awt.Font("Monaco", 1, 24)); // NOI18N
        SignupjButton.setForeground(new java.awt.Color(51, 51, 51));
        SignupjButton.setText("Sign Up");
        SignupjButton.setBorderPainted(false);
        SignupjButton.setContentAreaFilled(false);
        SignupjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupjButtonActionPerformed(evt);
            }
        });
        jPanel3.add(SignupjButton);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 280, 50));

        jPanel4.setBackground(new java.awt.Color(255, 204, 255));

        SigninjButton.setBackground(new java.awt.Color(129, 178, 154));
        SigninjButton.setFont(new java.awt.Font("Monaco", 1, 24)); // NOI18N
        SigninjButton.setForeground(new java.awt.Color(51, 51, 51));
        SigninjButton.setText("Sign In");
        SigninjButton.setBorderPainted(false);
        SigninjButton.setContentAreaFilled(false);
        SigninjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SigninjButtonActionPerformed(evt);
            }
        });
        jPanel4.add(SigninjButton);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 280, 50));

        NamejLabel.setFont(new java.awt.Font("Bahnschrift", 2, 24)); // NOI18N
        NamejLabel.setForeground(new java.awt.Color(255, 255, 255));
        NamejLabel.setText("Rehabilitation and care ");
        jPanel1.add(NamejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 260, 80));

        NamejLabel2.setFont(new java.awt.Font("Arial", 0, 58)); // NOI18N
        NamejLabel2.setForeground(new java.awt.Color(255, 204, 255));
        NamejLabel2.setText("HEAL EMPOWER RELIEF");
        jPanel1.add(NamejLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 730, 80));

        NamejLabel3.setFont(new java.awt.Font("Bahnschrift", 2, 24)); // NOI18N
        NamejLabel3.setForeground(new java.awt.Color(255, 255, 255));
        NamejLabel3.setText("We personally make sure that every acid attack victim is provided with the right treatment, legal support, ");
        jPanel1.add(NamejLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 1130, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 109, 1412, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignupjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupjButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignupjButton1ActionPerformed

    private void SigninjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SigninjButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SigninjButton1ActionPerformed

    private void SignupjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupjButtonActionPerformed
        this.dispose();
        SignUpJFrame eng = new SignUpJFrame();
        eng.setVisible(true);
    }//GEN-LAST:event_SignupjButtonActionPerformed

    private void SigninjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SigninjButtonActionPerformed
        this.dispose();
        SignInJFrame eng = new SignInJFrame();
        eng.setVisible(true);
    }//GEN-LAST:event_SigninjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try{
            UIManager.setLookAndFeel(new FlatDarculaLaf());
        } catch(Exception e){
            e.printStackTrace();
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NamejLabel;
    private javax.swing.JLabel NamejLabel1;
    private javax.swing.JLabel NamejLabel2;
    private javax.swing.JLabel NamejLabel3;
    private javax.swing.JButton SigninjButton;
    private javax.swing.JButton SigninjButton1;
    private javax.swing.JButton SignupjButton;
    private javax.swing.JButton SignupjButton1;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JPanel TopPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
