/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui.CaseReporter;
import ui.PhysicalExaminationCenter.*;
import business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Network.Network;
import business.Organization.CaseSupervisorOrganization;
import business.Organization.CaseReporterOrganization;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import business.WorkQueue.CaseReporterWorkRequest;
/**
 *
 * @author Jyothi
 */
public class ReportJPanel extends javax.swing.JPanel {

    /** Creates new form ReportJPanel */
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccount userAccount;
    CaseReporterOrganization organization;
    Network network;
    public ReportJPanel(JPanel userProcessContainer, EcoSystem system,UserAccount userAccount,Organization organization, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.userAccount = userAccount;
        this.organization = (CaseReporterOrganization) organization;
        this.network = network;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        namesurvivorjLabel = new javax.swing.JLabel();
        relationjLabel = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblDetails = new javax.swing.JLabel();
        lblSuspect = new javax.swing.JLabel();
        lblNameofSuspect = new javax.swing.JLabel();
        txtChildName = new javax.swing.JTextField();
        friendRadioButton = new javax.swing.JRadioButton();
        parentRadioButton = new javax.swing.JRadioButton();
        txtSuspectName = new javax.swing.JTextField();
        knownRadioButton = new javax.swing.JRadioButton();
        unknownRadioButton = new javax.swing.JRadioButton();
        txtMoreDetails = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        Selfradiobutton = new javax.swing.JRadioButton();
        otherRadioButton = new javax.swing.JRadioButton();
        dateOfIncident = new com.toedter.calendar.JDateChooser();
        ReportjButton = new javax.swing.JButton();
        comboBoxIncident = new javax.swing.JComboBox<>();
        txtAgeofChild = new javax.swing.JTextField();
        lblAgeofChild = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(59, 63, 66));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1570, 845));
        jPanel1.setPreferredSize(new java.awt.Dimension(1470, 700));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namesurvivorjLabel.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        namesurvivorjLabel.setForeground(new java.awt.Color(255, 255, 255));
        namesurvivorjLabel.setText("Name of Victim : ");
        jPanel1.add(namesurvivorjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 122, -1));

        relationjLabel.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        relationjLabel.setForeground(new java.awt.Color(255, 255, 255));
        relationjLabel.setText("Relation with Survivor : ");
        jPanel1.add(relationjLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 178, -1));

        lblType.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblType.setForeground(new java.awt.Color(255, 255, 255));
        lblType.setText("Severity of Burns:");
        jPanel1.add(lblType, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 140, 30));

        lblLocation.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblLocation.setForeground(new java.awt.Color(255, 255, 255));
        lblLocation.setText("Location of Incident :");
        jPanel1.add(lblLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 151, -1));

        lblDate.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("Date of Incident :");
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 126, 20));

        lblDetails.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblDetails.setForeground(new java.awt.Color(255, 255, 255));
        lblDetails.setText("More Details : ");
        jPanel1.add(lblDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 128, -1));

        lblSuspect.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblSuspect.setForeground(new java.awt.Color(255, 255, 255));
        lblSuspect.setText("Suspect :");
        jPanel1.add(lblSuspect, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 133, -1));

        lblNameofSuspect.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblNameofSuspect.setForeground(new java.awt.Color(255, 255, 255));
        lblNameofSuspect.setText("Name of Suspect : ");
        jPanel1.add(lblNameofSuspect, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 142, -1));

        txtChildName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChildNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtChildName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 235, -1));

        friendRadioButton.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        friendRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        friendRadioButton.setText("Friend");
        jPanel1.add(friendRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));

        parentRadioButton.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        parentRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        parentRadioButton.setText("Parent");
        parentRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(parentRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 79, -1));
        jPanel1.add(txtSuspectName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 241, -1));

        knownRadioButton.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        knownRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        knownRadioButton.setText("Known");
        knownRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knownRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(knownRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, -1, -1));

        unknownRadioButton.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        unknownRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        unknownRadioButton.setText("Unknown");
        jPanel1.add(unknownRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, -1));
        jPanel1.add(txtMoreDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 240, 50));
        jPanel1.add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 235, -1));

        Selfradiobutton.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        Selfradiobutton.setForeground(new java.awt.Color(255, 255, 255));
        Selfradiobutton.setText("Self");
        jPanel1.add(Selfradiobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 61, -1));

        otherRadioButton.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        otherRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        otherRadioButton.setText("Other");
        jPanel1.add(otherRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, -1, -1));
        jPanel1.add(dateOfIncident, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 240, -1));

        ReportjButton.setBackground(new java.awt.Color(255, 204, 204));
        ReportjButton.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        ReportjButton.setForeground(new java.awt.Color(255, 255, 255));
        ReportjButton.setText("Report");
        ReportjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportjButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ReportjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 119, -1));

        comboBoxIncident.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "First-degree(Superficial)", "Second-degree(Partial thickness)", "Third-degree(Full thickness)", "Fourth-degree" }));
        comboBoxIncident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxIncidentActionPerformed(evt);
            }
        });
        jPanel1.add(comboBoxIncident, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 240, -1));
        jPanel1.add(txtAgeofChild, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 235, -1));

        lblAgeofChild.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblAgeofChild.setForeground(new java.awt.Color(255, 255, 255));
        lblAgeofChild.setText("Age :");
        jPanel1.add(lblAgeofChild, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 45, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 633));
    }// </editor-fold>//GEN-END:initComponents

    private void txtChildNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChildNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChildNameActionPerformed

    private void parentRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_parentRadioButtonActionPerformed

    private void knownRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knownRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_knownRadioButtonActionPerformed

    private void ReportjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportjButtonActionPerformed

        CaseReporterWorkRequest request = new CaseReporterWorkRequest();
        request.setStatus("Waiting");
        request.setSender(userAccount);

        request.setChildName(txtChildName.getText());
        request.setEmail(txtAgeofChild.getText());
        //for choosing relations
        if(friendRadioButton.isSelected())
        {
            request.setRelation("Friend");
        }
        else if(parentRadioButton.isSelected())
        {
            request.setRelation("Parent");
        }
        else if(Selfradiobutton.isSelected())
        {
            request.setRelation("Self");

        }
        else if(otherRadioButton.isSelected())
        {
            request.setRelation("Other");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a relation");

        }
        //for choosing type
        if(comboBoxIncident.getSelectedItem().toString().equalsIgnoreCase("Select one"))
        {
            JOptionPane.showMessageDialog(null, "Please select a type");
        }
        else{
            request.setAssaultType(comboBoxIncident.getSelectedItem().toString());
        }
        //location
        request.setLocation(txtLocation.getText());
        //date
        if(dateOfIncident.getDate()==null)
        {
            JOptionPane.showMessageDialog(null, "Please select a date");
        }else{
            request.setDoi(dateOfIncident.getDate());
        }
        //more detaisl
        if(txtMoreDetails.getText()==null)
        {
            JOptionPane.showMessageDialog(null, "Please fill more details");
            return;
        }
        request.setMoredetails(txtMoreDetails.getText());
        //suspect
        if(knownRadioButton.isSelected())
        {
            request.setSuspecttype("Known");
        }
        else if(unknownRadioButton.isSelected())
        {
            request.setSuspecttype("Unknown");
        }else{JOptionPane.showMessageDialog(null, "Please select a suspect type");}

        //name of suspect
        request.setNameofsuspect(txtSuspectName.getText());

        if(request.getDoi()!=null && request.getLocation()!=null && request.getRelation()!=null && request.getSuspecttype()!=null
            && request.getChildName()!=null && request.getAssaultType()!=null)
        {
            Enterprise e= network.getEnterpriseDirectory().searchEnterprisebyType(Enterprise.EnterpriseType.ASIT);
            Organization org = null;
            for (Organization organization : e.getOrganizationDirectory().getOrganizationList()){
                if (organization instanceof CaseSupervisorOrganization){
                    org = organization;
                    break;
                }
            }
            if (org!=null){
                org.getWorkQueue().getCaseReporterWorkRequestList().add(request);
                //userAccount.getWorkQueue().CaseReporterWorkRequestList().add(request);
            }

            txtChildName.setText("");
            txtSuspectName.setText("");
            txtMoreDetails.setText("");
            txtLocation.setText("");
            txtAgeofChild.setText("");
            friendRadioButton.setSelected(false);
            parentRadioButton.setSelected(false);
            Selfradiobutton.setSelected(false);
            otherRadioButton.setSelected(false);
            knownRadioButton.setSelected(false);
            unknownRadioButton.setSelected(false);
            comboBoxIncident.setSelectedIndex(0);
            // dateOfIncident.setDate(null);
            userAccount.getWrkQue().getCaseReporterWorkRequestList().add(request);

            JOptionPane.showMessageDialog(null, "Incident is reported successfully.");

        }
    }//GEN-LAST:event_ReportjButtonActionPerformed

    private void comboBoxIncidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxIncidentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxIncidentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReportjButton;
    private javax.swing.JRadioButton Selfradiobutton;
    private javax.swing.JComboBox<String> comboBoxIncident;
    private com.toedter.calendar.JDateChooser dateOfIncident;
    private javax.swing.JRadioButton friendRadioButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton knownRadioButton;
    private javax.swing.JLabel lblAgeofChild;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDetails;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblNameofSuspect;
    private javax.swing.JLabel lblSuspect;
    private javax.swing.JLabel lblType;
    private javax.swing.JLabel namesurvivorjLabel;
    private javax.swing.JRadioButton otherRadioButton;
    private javax.swing.JRadioButton parentRadioButton;
    private javax.swing.JLabel relationjLabel;
    private javax.swing.JTextField txtAgeofChild;
    private javax.swing.JTextField txtChildName;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtMoreDetails;
    private javax.swing.JTextField txtSuspectName;
    private javax.swing.JRadioButton unknownRadioButton;
    // End of variables declaration//GEN-END:variables

}
