/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.Lawyer;

import business.EcoSystem;
import business.Enterprise.Enterprise;
import business.Network.Network;
import business.Organization.CaseSupervisorOrganization;
import business.Organization.PhysicalExaminationCenterOrganization;
import business.Organization.Organization;
import business.UserAccount.UserAccount;
import business.WorkQueue.LawyerWorkRequest;
import business.WorkQueue.CaseReporterWorkRequest;
import business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author rohit
 */
public class CaseReportLJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CaseReportLJPanel
     */
    
    JPanel userProcessContainer;
    EcoSystem system;
    CaseReporterWorkRequest request;
    UserAccount userAccount;
    Network network;
    
    public CaseReportLJPanel(JPanel userProcessContainer, EcoSystem system, CaseReporterWorkRequest request,UserAccount userAccount, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.request = request;
        this.userAccount = userAccount;
        this.network = network;
        PopulateReport();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblRelationwithSurvivor = new javax.swing.JLabel();
        lblTypeofAssault = new javax.swing.JLabel();
        lbllocation = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblSuspectType = new javax.swing.JLabel();
        lblSuspectName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtSuspectName = new javax.swing.JTextField();
        txtlocation = new javax.swing.JTextField();
        txtRelationwithSurvivor = new javax.swing.JTextField();
        txtTypeofAssault = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtSuspectType = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(59, 63, 66));

        jPanel1.setBackground(new java.awt.Color(59, 63, 66));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblName.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name of Survivor : ");
        jPanel1.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 162, -1));

        lblRelationwithSurvivor.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblRelationwithSurvivor.setForeground(new java.awt.Color(255, 255, 255));
        lblRelationwithSurvivor.setText("Relation with Survivor : ");
        jPanel1.add(lblRelationwithSurvivor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 172, -1));

        lblTypeofAssault.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblTypeofAssault.setForeground(new java.awt.Color(255, 255, 255));
        lblTypeofAssault.setText("Severity of Burns: ");
        jPanel1.add(lblTypeofAssault, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        lbllocation.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lbllocation.setForeground(new java.awt.Color(255, 255, 255));
        lbllocation.setText("Location of Incident :");
        jPanel1.add(lbllocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        lblDate.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblDate.setForeground(new java.awt.Color(255, 255, 255));
        lblDate.setText("Date of Incident :");
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        lblSuspectType.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblSuspectType.setForeground(new java.awt.Color(255, 255, 255));
        lblSuspectType.setText("Suspect :");
        jPanel1.add(lblSuspectType, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 138, -1));

        lblSuspectName.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblSuspectName.setForeground(new java.awt.Color(255, 255, 255));
        lblSuspectName.setText("Name of Suspect : ");
        jPanel1.add(lblSuspectName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 159, -1));

        txtName.setEditable(false);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 234, -1));
        jPanel1.add(txtSuspectName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 240, -1));

        txtlocation.setEditable(false);
        jPanel1.add(txtlocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 234, -1));

        txtRelationwithSurvivor.setEditable(false);
        txtRelationwithSurvivor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRelationwithSurvivorActionPerformed(evt);
            }
        });
        jPanel1.add(txtRelationwithSurvivor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 234, -1));

        txtTypeofAssault.setEditable(false);
        txtTypeofAssault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeofAssaultActionPerformed(evt);
            }
        });
        jPanel1.add(txtTypeofAssault, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 234, -1));

        txtDate.setEditable(false);
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 234, -1));
        jPanel1.add(txtSuspectType, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 240, -1));

        btnBack.setBackground(new java.awt.Color(255, 204, 204));
        btnBack.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnBack)
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtRelationwithSurvivorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRelationwithSurvivorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRelationwithSurvivorActionPerformed

    private void txtTypeofAssaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeofAssaultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeofAssaultActionPerformed

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        btnBack.setForeground(new Color(0,128,128));        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        btnBack.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackMouseExited

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LawyerJPanel sysAdminwjp = (LawyerJPanel) component;
        //sysAdminwjp.populateTree();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblRelationwithSurvivor;
    private javax.swing.JLabel lblSuspectName;
    private javax.swing.JLabel lblSuspectType;
    private javax.swing.JLabel lblTypeofAssault;
    private javax.swing.JLabel lbllocation;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRelationwithSurvivor;
    private javax.swing.JTextField txtSuspectName;
    private javax.swing.JTextField txtSuspectType;
    private javax.swing.JTextField txtTypeofAssault;
    private javax.swing.JTextField txtlocation;
    // End of variables declaration//GEN-END:variables

    private void PopulateReport() {
        txtName.setText(request.getChildName());
        txtRelationwithSurvivor.setText(request.getRelation());
        txtTypeofAssault.setText(request.getAssaultType());
        txtlocation.setText(request.getLocation());
        txtDate.setText(request.getDoi().toString());
        txtSuspectType.setText(request.getSuspecttype());
        txtSuspectName.setText(request.getNameofsuspect());
        
        
    }
}
